sonar.sources=app/src/main/java,core/src/main/java,plugin/src/main/java,maven-plugin/src/main/java
sonar.tests=core/src/test/java
sonar.java.binaries=app/build/classes/java/main,core/build/classes/java/main,plugin/build/classes/java/main,maven-plugin/target/classes
sonar.java.test.binaries=core/build/classes/java/test
sonar.exclusions=**/build/**,**/target/**,examples/**,schemas/**
sonar.sourceEncoding=UTF-8
